Make services optional in converters
This hopefully helps to avoid runtime exceptions such as:

[ERROR] Cannot create plugin: class='net.imagej.legacy.translate.DatasetImagePlusConverter', priority=-100.0, enabled=true, pluginType=Converter
java.lang.IllegalArgumentException: Required service is missing: net.imagej.legacy.LegacyService
Context: org.scijava.Context@62ef27a8
ClassLoader: sun.misc.Launcher$AppClassLoader@6e0be858

-- Services known to context --
org.scijava.event.DefaultEventService [priority = 100000.0]
org.scijava.script.DefaultScriptService [priority = 100.0]
io.scif.services.SCIFIODatasetService [priority = 1.0]
net.imagej.DefaultDatasetService [priority = 0.0]
net.imagej.types.DefaultDataTypeService [priority = 0.0]
org.scijava.app.DefaultAppService [priority = 0.0]
org.scijava.command.DefaultCommandService [priority = 0.0]
org.scijava.convert.DefaultConvertService [priority = 0.0]
org.scijava.module.DefaultModuleService [priority = 0.0]
org.scijava.object.DefaultObjectService [priority = 0.0]
org.scijava.parse.DefaultParseService [priority = 0.0]
org.scijava.plugin.DefaultPluginService [priority = 0.0]
org.scijava.prefs.DefaultPrefService [priority = 0.0]
org.scijava.thread.DefaultThreadService [priority = 0.0]
org.scijava.log.StderrLogService [priority = -100.0]

-- Classpath of ClassLoader --
/Users/curtis/code/imagej/imagej-legacy/target/surefire/surefirebooter7111243332339140593.jar

       	at org.scijava.Context.inject(Context.java:450)
       	at org.scijava.Context.inject(Context.java:381)
       	at org.scijava.plugin.DefaultPluginService.createInstance(DefaultPluginService.java:237)
       	at org.scijava.plugin.DefaultPluginService.createInstances(DefaultPluginService.java:225)
       	at org.scijava.plugin.DefaultPluginService.createInstancesOfType(DefaultPluginService.java:216)
       	at org.scijava.plugin.AbstractSingletonService.initInstances(AbstractSingletonService.java:92)
       	at org.scijava.plugin.AbstractSingletonService.getInstances(AbstractSingletonService.java:75)
       	at org.scijava.plugin.AbstractHandlerService.getHandler(AbstractHandlerService.java:49)
       	at org.scijava.util.ConversionUtils.handler(ConversionUtils.java:316)
       	at org.scijava.util.ConversionUtils.convert(ConversionUtils.java:250)
       	at org.scijava.command.CommandModuleItem.tValue(CommandModuleItem.java:252)
       	at org.scijava.command.CommandModuleItem.tValue(CommandModuleItem.java:246)
       	at org.scijava.command.CommandModuleItem.getMinimumValue(CommandModuleItem.java:138)
       	at org.scijava.module.DefaultMutableModuleItem.<init>(DefaultMutableModuleItem.java:121)
       	at org.scijava.command.DynamicCommandInfo.copy(DynamicCommandInfo.java:313)
       	at org.scijava.command.DynamicCommandInfo.populateItems(DynamicCommandInfo.java:304)
       	at org.scijava.command.DynamicCommandInfo.<init>(DynamicCommandInfo.java:73)
       	at org.scijava.command.DynamicCommand.getInfo(DynamicCommand.java:74)
       	at org.scijava.options.OptionsPlugin.load(OptionsPlugin.java:93)
       	at org.scijava.options.DefaultOptionsService.getInstances(DefaultOptionsService.java:91)
       	at org.scijava.plugin.SingletonService$1.get(SingletonService.java:101)
       	at org.scijava.plugin.SingletonService$1.get(SingletonService.java:97)
       	at org.scijava.object.ObjectIndex.resolvePending(ObjectIndex.java:387)
       	at org.scijava.object.ObjectIndex.get(ObjectIndex.java:132)
       	at org.scijava.object.DefaultObjectService.getObjects(DefaultObjectService.java:86)
       	at org.scijava.module.DefaultModuleService.getRegisteredModuleInstance(DefaultModuleService.java:394)
       	at org.scijava.module.DefaultModuleService.createModule(DefaultModuleService.java:167)
       	at org.scijava.module.DefaultModuleService.run(DefaultModuleService.java:210)
       	at org.scijava.module.DefaultModuleService.run(DefaultModuleService.java:201)
       	at org.scijava.module.DefaultModuleService.run(DefaultModuleService.java:186)
       	at org.scijava.script.DefaultScriptService.run(DefaultScriptService.java:224)
       	at org.scijava.script.DefaultScriptService.run(DefaultScriptService.java:210)
       	at org.scijava.script.DefaultScriptService.run(DefaultScriptService.java:196)
       	at net.imagej.legacy.LegacyOpenerTest.testSliceLabels(LegacyOpenerTest.java:124)