Rename Manual Threshold script to avoid ellipsis
Multiple period characters in a row breaks certain tooling:

> I get this error using a new (2024-03 (4.31.0)) eclipse
>
> > A save participant caused problems.
> >   The save participant 'Code Clean Up' caused an exception:
> >   java.lang.IllegalArgumentException: Bad zip entry:
> >   scripts/Image/Adjust/Manual_Threshold....js in
> >   .../.m2/repository/net/imagej/imagej-legacy/1.2.0/imagej-legacy-1.2.0.jar.
> >   See the error log for details.

https://imagesc.zulipchat.com/#narrow/stream/327238-Fiji/topic/eclipse.20complains.20about.20imagej-legacy.20jar